[package]
name = "vulkan_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
env_logger = "0.11.8"
log = "0.4.27"
raw-window-handle = "0.6.2"
winit = "0.30.11"
